name: bank_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^9.0.0

  font_awesome_flutter: ^10.8.0

  flutter_svg: ^2.0.17

  cupertino_icons: ^1.0.8

  google_fonts: ^6.2.1

  gap: ^3.0.1

  lottie: ^3.3.1

  freezed: ^2.5.8

  appwrite: ^13.1.1

  get_it: ^8.0.3

  bloc_test: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  build_runner: any

  json_serializable: ^6.8.0

dependency_overrides:
  web_socket_channel: ^2.2.0
  analyzer:

flutter_gen:
  integrations:
    flutter_svg: true

flutter:

  uses-material-design: true

  assets:
    - assets/
